datasources: 
  pit_stops: 
    name: '../DATASETS/pit_stops.csv'
    base: true
  races: 
    name: '../DATASETS/races.csv'
    mergeLogic:
      base: raceId
      field: raceId
    rename:
      url: urlRaces
      name: nameRaces
      year: yearRaces
  drivers:
    name: "../DATASETS/drivers.csv"
    mergeLogic:
      base: driverId
      field: driverId
    rename: 
      url: urlDrivers
      nationality: nationalityDrivers
  circuits:
    name: "../DATASETS/circuits.csv"
    mergeLogic:
      base: circuitId
      field: circuitId
    rename:
      name: nameCircuits
      country: countryCircuits
      alt: altitude
      lat: latitude
      lng: longitude
      url: urlCircuits

database:
  sqlScript: './f1_pit_stops.sql'
  user: root
  password: admin
  host: localhost
  port: 3306
  name: f1_pit_stops

tables:
  dim_driver:
    driver_nk :
      value: driverId
    driver_ref: 
      value: driverRef
    code: 
      value: code
    forename: 
      value: forename
    surname: 
      value: surname
    nationality: 
      value: nationalityDrivers
    number: 
      value: number
    url: 
      value: urlDrivers

  dim_circuit:
    circuit_nk: 
      value: circuitId
    circuit_ref: 
      value: circuitRef
    name: 
      value: nameCircuits
    location: 
      value: location
    country: 
      value: countryCircuits
    altitude: 
      value: altitude
    latitude: 
      value: latitude
    longitude: 
      value: longitude
    url: 
      value: urlCircuits

  dim_date:
    date: 
      value: date
    year: {value: date, date: true}
    month: {value: date, date: true}
    day: {value: date, date: true}

  dim_race:
    race_nk: 
      value: raceId
    name: 
      value: nameRaces
    round: 
      value: round
    year: { value: date, date: true }
    url: 
      value: urlRaces

  fact_pit_stops:
    race_id: {fk: dim_race}
    driver_id: {fk: dim_driver}
    circuit_id: {fk: dim_circuit}
    date_id: {fk: dim_date}

    stop: 
      value: stop
    lap: 
      value:  lap
    duration_ms: 
      value:  milliseconds

config:
  dim_driver:
    design: dimension
    id: driver_id
    onDuplicate:
      criteria: driver_nk
      method: ignore
    onNull:
      method: default
      criteria:
        driver_nk: null

  dim_circuit:
    design: dimension
    id: circuit_id
    onDuplicate:
      criteria: circuit_nk
      method: ignore
    onNull:
      method: default
      criteria:
        circuit_nk: null

  dim_date:
    design: dimension
    id: date_id
    onDuplicate:
      criteria: [year, month, day]
      method: ignore
    onNull:
      method: default
      criteria:
        date: null

  dim_race:
    design: dimension
    id: race_id
    onDuplicate:
      criteria: race_nk
      method: ignore
    onNull:
      method: default
      criteria:
        race_nk: null

  fact_pit_stops:
    design: fact
    id: pit_stop_id
    onDuplicate:
      criteria: [race_id, driver_id, stop, lap]
      method: update
    
    onNull:
      method: default
      criteria:
        race_id: null
        driver_id: null
        constructor_id: null
        circuit_id: null
        date_id: null
        stop: -1
        lap: -1
        duration_ms: -1
        
