datasources:
  qualifying:
    name: "../DATASETS/qualifying.csv"
    base: true
  races:
    name: "../DATASETS/races.csv"
    mergeLogic:
      base: raceId
      field: raceId
    rename:
      name: nameRaces
      url: urlRaces
      year: yearRaces
  drivers:
    name: "../DATASETS/drivers.csv"
    mergeLogic:
      base: driverId
      field: driverId
    rename:
      url: urlDrivers
      nationality: nationalityDrivers
  circuits:
    name: "../DATASETS/circuits.csv"
    mergeLogic:
      base: circuitId
      field: circuitId
    rename:
      name: nameCircuits
      country: countryCircuits
      alt: altitude
      lat: latitude
      lng: longitude
      url: urlCircuits

  constructors:
    name: "../DATASETS/constructors.csv"
    mergeLogic:
      base: constructorId
      field: constructorId
    rename:
      name: nameConstructors
      nationality: nationalityConstructors
      url: urlConstructors

database:
  sqlScript: "./f1_qualifying.sql"
  user: root
  password: admin
  host: localhost
  port: 3306
  name: f1_qualifying

tables:
  dim_driver:
    driver_nk:
      value: driverId
    driver_ref:
      value: driverRef
    code:
      value: code
    forename:
      value: forename
    surname:
      value: surname
    nationality:
      value: nationalityDrivers
    number:
      value: number

  dim_constructor:
    constructor_nk:
      value: constructorId
    constructor_ref:
      value: constructorRef
    name:
      value: nameConstructors
    nationality:
      value: nationalityConstructors
    url:
      value: urlConstructors

  dim_circuit:
    circuit_nk:
      value: circuitId
    circuit_ref:
      value: circuitRef
    name:
      value: nameCircuits
    location:
      value: location
    country:
      value: countryCircuits
    altitude:
      value: altitude
    latitude:
      value: latitude
    longitude:
      value: longitude
    url:
      value: urlCircuits

  dim_date:
    date:
     value: date
    year: { value: date, date: true }
    month: { value: date, date: true }
    day: { value: date, date: true }

  dim_race:
    race_nk:
      value: raceId
    name:
      value: nameRaces
    round:
      value: round
    year: { value: date, date: true }
    url:
      value: urlRaces

  fact_qualifying:
    race_id: { fk: dim_race }
    driver_id: { fk: dim_driver }
    constructor_id: { fk: dim_constructor }
    circuit_id: { fk: dim_circuit }
    date_id: { fk: dim_date }

    q1_str:
      value: q1
    q2_str:
      value: q2
    q3_str:
      value: q3

    q1_sec: { value: q1, duration_sec: true }
    q2_sec: { value: q2, duration_sec: true }
    q3_sec: { value: q3, duration_sec: true }

    position: position

config:
  dim_driver:
    design: dimension
    id: driver_id
    onDuplicate:
      criteria: driver_nk
      method: ignore
    onNull:
      method: default
      criteria:
        driver_nk: null

  dim_constructor:
    design: dimension
    id: constructor_id
    onDuplicate:
      criteria: constructor_nk
      method: ignore
    onNull:
      method: default
      criteria:
        constructor_nk: null

  dim_circuit:
    design: dimension
    id: circuit_id
    onDuplicate:
      criteria: circuit_nk
      method: ignore
    onNull:
      method: default
      criteria:
        circuit_nk: null

  dim_date:
    design: dimension
    id: date_id
    onDuplicate:
      criteria: [year, month, day]
      method: ignore
    onNull:
      method: default
      criteria:
        date: null

  dim_race:
    design: dimension
    id: race_id
    onDuplicate:
      criteria: race_nk
      method: ignore
    onNull:
      method: default
      criteria:
        race_nk: null

  fact_qualifying:
    design: fact
    id: qualifying_id
    onDuplicate:
      criteria: [race_id, driver_id]
      method: update

    onNull:
      method: default
      criteria:
        race_id: null
        driver_id: null
        constructor_id: null
        circuit_id: null
        date_id: null
        q1_sec: null
        q2_sec: null
        q3_sec: null
        q1_str: null
        q2_str: null
        q3_str: null
        position: null
