datasources:
  race_results:
    name: "../DATASETS/results.csv"
    base: true
  races:
    name: "../DATASETS/races.csv"
    mergeLogic:
      base: raceId
      field: raceId
    rename:
      name: nameRaces
      url: urlRaces
      year: yearRaces
  drivers:
    name: "../DATASETS/drivers.csv"
    mergeLogic:
      base: driverId
      field: driverId
    rename:
      url: urlDrivers
      nationality: nationalityDrivers
  circuits:
    name: "../DATASETS/circuits.csv"
    mergeLogic:
      base: circuitId
      field: circuitId
    rename:
      name: nameCircuits
      country: countryCircuits
      alt: altitude
      lat: latitude
      lng: longitude
      url: urlCircuits
  constructors:
    name: "../DATASETS/constructors.csv"
    mergeLogic:
      base: constructorId
      field: constructorId
    rename:
      name: nameConstructors
      nationality: nationalityConstructors
      url: urlConstructors
  status:
    name: "../DATASETS/status.csv"
    mergeLogic:
      base: statusId
      field: statusId

database:
  sqlScript: "./f1_race_results.sql"
  user: root
  password: admin
  host: localhost
  port: 3306
  name: f1_race_results

tables:
  dim_driver:
    driver_nk:
      value: driverId
    driver_ref:
      value: driverRef
      normalize_ref: true
    code:
      value: code
      upper: true
    forename:
      value: forename
      strip: true
      title: true
    surname:
      value: surname
      strip: true
      title: true
    nationality:
      value: nationalityDrivers
      title: true
    number:
      value: number
      int: true
    url:
      value: urlDrivers

  dim_constructor:
    constructor_nk:
      value: constructorId
    constructor_ref:
      value: constructorRef
      normalize_ref: true
    name:
      value: nameConstructors
      strip: true
      title: true
    nationality:
      value: nationalityConstructors
      title: true
    url:
      value: urlConstructors

  dim_circuit:
    circuit_nk:
      value: circuitId
    circuit_ref:
      value: circuitRef
      normalize_ref: true
    name:
      value: nameCircuits
      strip: true
      title: true
    location:
      value: location
      strip: true
      title: true
    country:
      value: countryCircuits
      strip: true
      title: true
    altitude:
      value: altitude
      int: true
    latitude:
      value: latitude
      float: true
      decimals: 6
    longitude:
      value: longitude
      float: true
      decimals: 6
    url:
      value: urlCircuits

  dim_date:
    date: { value: date }
    year: { value: date, date: true }
    month: { value: date, date: true }
    day: { value: date, date: true }

  dim_race:
    race_nk:
      value: raceId
    name:
      value: nameRaces
      strip: true
      title: true
    round:
      value: round
      int: true
    year: { value: date, date: true }
    url:
      value: urlRaces

  dim_status:
    status_nk:
      value: statusId
    status_name:
      value: status
      strip: true
      title: true

  fact_race_result:
    race_id: { fk: dim_race }
    driver_id: { fk: dim_driver }
    constructor_id: { fk: dim_constructor }
    circuit_id: { fk: dim_circuit }
    date_id: { fk: dim_date }
    status_id: { fk: dim_status }

    initial_position:
      value: grid
      int: true
    final_position:
      value: position
      int: true
    ranking_position:
      value: positionOrder
      int: true
    points:
      value: points
      float: true
    laps:
      value: laps
      int: true

    time_str:
      value: time
    time_ms:
      value: milliseconds
      int: true

    fastest_lap:
      value: fastestLap
      int: true
    fastest_lap_time_str:
      value: fastestLapTime
    fastest_lap_time_ms: { value: fastestLapTime, duration_sec: true }
    fastest_lap_top_speed:
      value: fastestLapSpeed
      float: true

config:
  dim_driver:
    design: dimension
    id: driver_id
    onDuplicate:
      criteria: driver_nk
      method: ignore
    onNull:
      require: [driver_nk, driver_ref, forename, surname]

  dim_constructor:
    design: dimension
    id: constructor_id
    onDuplicate:
      criteria: constructor_nk
      method: ignore
    onNull:
      require: [constructor_nk, constructor_ref, name]

  dim_circuit:
    design: dimension
    id: circuit_id
    onDuplicate:
      criteria: circuit_nk
      method: ignore
    onNull:
      require: [circuit_nk, circuit_ref, name, location, country]

  dim_date:
    design: dimension
    id: date_id
    onDuplicate:
      criteria: [year, month, day]
      method: ignore
    onNull:
      require: [date, year, month, day]

  dim_race:
    design: dimension
    id: race_id
    onDuplicate:
      criteria: race_nk
      method: ignore
    onNull:
      require: [race_nk, name, round, year]

  dim_status:
    design: dimension
    id: status_id
    onDuplicate:
      criteria: status_nk
      method: ignore
    onNull:
      require: [status_nk, status_name]

  fact_race_result:
    design: fact
    id: race_result_id
    onDuplicate:
      criteria: [race_id, driver_id]
      method: update

    onNull:
      require:
        [race_id, driver_id, constructor_id, circuit_id, date_id, status_id]
