datasources:
  race_results:
    name: "../DATASETS/results.csv"
    base: true
  races:
    name: "../DATASETS/races.csv"
    mergeLogic:
      base: raceId
      field: raceId
    rename:
      name: nameRaces
      url: urlRaces
      year: yearRaces
  drivers:
    name: "../DATASETS/drivers.csv"
    mergeLogic:
      base: driverId
      field: driverId
    rename:
      url: urlDrivers
      nationality: nationalityDrivers
  circuits:
    name: "../DATASETS/circuits.csv"
    mergeLogic:
      base: circuitId
      field: circuitId
    rename:
      name: nameCircuits
      country: countryCircuits
      alt: altitude
      lat: latitude
      lng: longitude
      url: urlCircuits
  constructors:
    name: "../DATASETS/constructors.csv"
    mergeLogic:
      base: constructorId
      field: constructorId
    rename:
      name: nameConstructors
      nationality: nationalityConstructors
      url: urlConstructors
  status:
    name: "../DATASETS/status.csv"
    mergeLogic:
      base: statusId
      field: statusId

database:
  sqlScript: "./f1_race_results.sql"
  user: root
  password: admin
  host: localhost
  port: 3306
  name: f1_race_results

tables:
  dim_driver:
    driver_nk:
      value: driverId
    driver_ref:
      value: driverRef
    code:
      value: code
    forename:
      value: forename
    surname:
      value: surname
    nationality:
      value: nationalityDrivers
    number:
      value: number

  dim_constructor:
    constructor_nk:
      value: constructorId
    constructor_ref:
      value: constructorRef
    name:
      value: nameConstructors
    nationality:
      value: nationalityConstructors
    url:
      value: urlConstructors

  dim_circuit:
    circuit_nk:
      value: circuitId
    circuit_ref:
      value: circuitRef
    name:
      value: nameCircuits
    location:
      value: location
    country:
      value: countryCircuits
    altitude:
      value: altitude
    latitude:
      value: latitude
    longitude:
      value: longitude

  dim_date:
    date: { value: date }
    year: { value: date, date: true }
    month: { value: date, date: true }
    day: { value: date, date: true }

  dim_race:
    race_nk:
      value: raceId
    name:
      value: nameRaces
    round:
      value: round
    year: { value: date, date: true }
    url: urlRaces

  dim_status:
    status_nk: 
      value: statusId
    status_name: 
      value: status

  fact_race_result:
    race_id: { fk: dim_race }
    driver_id: { fk: dim_driver }
    constructor_id: { fk: dim_constructor }
    circuit_id: { fk: dim_circuit }
    date_id: { fk: dim_date }
    status_id: { fk: dim_status }

    initial_position: 
      value: grid
    final_position:
      value: position
    ranking_position:
      value: positionOrder
    points:
      value: points
    laps:
      value: laps

    time_str:
      value: time
    time_ms: { value: milliseconds, duration: true }

    fastest_lap:
      value: fastestLap
    fastest_lap_time_str:
      value: fastestLapTime
    fastest_lap_time_ms: { value: fastestLapTime, duration_sec: true }
    fastest_lap_top_speed:
      value: fastestLapSpeed

config:
  dim_driver:
    design: dimension
    id: driver_id
    onDuplicateDS:
      criteria: driver_nk
      method: ignore
    onDuplicateDB:
      criteria: driver_nk
      method: ignore
    onNull:
      method: default
      criteria:
        driver_nk: null

  dim_constructor:
    design: dimension
    id: constructor_id
    onDuplicateDS:
      criteria: constructor_nk
      method: ignore
    onDuplicateDB:
      criteria: constructor_nk
      method: ignore
    onNull:
      method: default
      criteria:
        constructor_nk: null

  dim_circuit:
    design: dimension
    id: circuit_id
    onDuplicateDS:
      criteria: circuit_nk
      method: ignore
    onDuplicateDB:
      criteria: circuit_nk
      method: ignore
    onNull:
      method: default
      criteria:
        circuit_nk: null

  dim_date:
    design: dimension
    id: date_id
    onDuplicateDS:
      criteria: [year, month, day]
      method: ignore
    onDuplicateDB:
      criteria: [year, month, day]
      method: ignore
    onNull:
      method: default
      criteria:
        date: null

  dim_race:
    design: dimension
    id: race_id
    onDuplicateDS:
      criteria: race_nk
      method: ignore
    onDuplicateDB:
      criteria: race_nk
      method: ignore
    onNull:
      method: default
      criteria:
        race_nk: null

  dim_status:
    design: dimension
    id: status_id
    onDuplicateDS:
      criteria: status_nk
      method: ignore
    onDuplicateDB:
      criteria: status_nk
      method: ignore
    onNull:
      method: default
      criteria:
        status_nk: null

  fact_race_result:
    design: fact
    id: race_result_id
    onDuplicateDS:
      criteria: [race_id, driver_id]
      method: ignore
    onDuplicateDB:
      criteria: [race_id, driver_id]
      method: update

    onNull:
      method: default
      criteria:
        race_id: null
        driver_id: null
        constructor_id: null
        circuit_id: null
        date_id: null
        status_id: null

        initial_position: null
        final_position: null
        ranking_position: null
        points: 0
        laps: 0
        time_str: "00:00:00"
        time_ms: 0
        fastest_lap: null
        fastest_lap_time_ms: 0
        fastest_lap_top_speed: null
