datasources: 
  pit_stops: 
    name: '../DATASETS/pit_stops.csv'
    base: true
  races: 
    name: '../DATASETS/races.csv'
    mergeLogic:
      base: raceId
      field: raceId
    rename:
      url: urlRaces
      name: nameRaces
      year: yearRaces
  drivers:
    name: "../DATASETS/drivers.csv"
    mergeLogic:
      base: driverId
      field: driverId
    rename: 
      url: urlDrivers
      nationality: nationalityDrivers
  circuits:
    name: "../DATASETS/circuits.csv"
    mergeLogic:
      base: circuitId
      field: circuitId
    rename:
      name: nameCircuits
      country: countryCircuits
      alt: altitude
      lat: latitude
      lng: longitude
      url: urlCircuits

database:
  sqlScript: './f1_pit_stops.sql'
  user: root
  password: admin
  host: localhost
  port: 3306
  name: f1_pit_stops

# Mapping of source fields to target table fields, including normalization rules
tables:
  dim_driver:
    driver_nk :
      value: driverId
    driver_ref: 
      value: driverRef
      normalize_ref: true
    code: 
      value: code
      upper: true
    forename: 
      value: forename
      strip: true
      title: true
    surname: 
      value: surname
      strip: true
      title: true
    nationality: 
      value: nationalityDrivers
      title: true
    number: 
      value: number
      int: true
    url: 
      value: urlDrivers

  dim_circuit:
    circuit_nk: 
      value: circuitId
    circuit_ref: 
      value: circuitRef
      normalize_ref: true
    name: 
      value: nameCircuits
      strip: true
      title: true
    location: 
      value: location
      strip: true
      title: true
    country: 
      value: countryCircuits
      strip: true
      title: true
    altitude: 
      value: altitude
      int: true
    latitude: 
      value: latitude
      float: true
      decimals: 4     # 4 should be enough for lat/long precision
    longitude: 
      value: longitude
      float: true
      decimals: 4
    url: 
      value: urlCircuits

  dim_date:
    date: 
      value: date
    year: {value: date, date: true}
    month: {value: date, date: true}
    day: {value: date, date: true}

  dim_race:
    race_nk: 
      value: raceId
    name: 
      value: nameRaces
      strip: true
      title: true
    round: 
      value: round
      int: true
    year: { value: date, date: true }
    url: 
      value: urlRaces

  fact_pit_stops:
    race_id: {fk: dim_race}
    driver_id: {fk: dim_driver}
    circuit_id: {fk: dim_circuit}
    date_id: {fk: dim_date}

    stop: 
      value: stop
      int: true
    lap: 
      value:  lap
      int: true
    duration_ms: 
      value: milliseconds
      int: true

# Require for each table the essential fields to be non-null, otherwise the record is not useful
# Also define the criteria for handling duplicates (ignore or update)
config:
  dim_driver:
    design: dimension
    id: driver_id
    onDuplicateDS:
      criteria: driver_nk
      method: ignore
    onDuplicateDB:
      criteria: driver_nk
      method: ignore 
    onNull:
      require: [driver_nk, driver_ref, forename, surname]

  dim_circuit:
    design: dimension
    id: circuit_id
    onDuplicateDS:
      criteria: circuit_nk
      method: ignore
    onDuplicateDB:
      criteria: circuit_nk
      method: ignore
    onNull:
      require: [circuit_nk, circuit_ref, name, location, country]

  dim_date:
    design: dimension
    id: date_id
    onDuplicateDS:
      criteria: [year, month, day]
      method: ignore
    onDuplicateDB:
      criteria: [year, month, day]
      method: ignore
    onNull:
      require: [date, year, month, day]

  dim_race:
    design: dimension
    id: race_id
    onDuplicateDS:
      criteria: race_nk
      method: ignore
    onDuplicateDB:
      criteria: race_nk
      method: ignore
    onNull:
      require: [race_nk, name, round, year]


  fact_pit_stops:
    design: fact
    id: pit_stop_id
    onDuplicateDS:
      criteria: [race_id, driver_id, stop, lap]
      method: ignore
    onDuplicateDB:
      criteria: [race_id, driver_id, stop, lap]
      method: update    
      method: update

    # Some values can be null (e.g. time if not recorded), so we do not require them
    # Require foreign keys and essential fields, which if null then there is no point in keeping the record
    onNull:
      require: [race_id, driver_id, circuit_id, date_id, stop, lap, duration_ms]

        
