datasources:
  qualifying:
    name: "../DATASETS/qualifying.csv"
    base: true
  races:
    name: "../DATASETS/races.csv"
    mergeLogic:
      base: raceId
      field: raceId
    rename:
      name: nameRaces
      url: urlRaces
      year: yearRaces
  drivers:
    name: "../DATASETS/drivers.csv"
    mergeLogic:
      base: driverId
      field: driverId
    rename:
      url: urlDrivers
      nationality: nationalityDrivers
  circuits:
    name: "../DATASETS/circuits.csv"
    mergeLogic:
      base: circuitId
      field: circuitId
    rename:
      name: nameCircuits
      country: countryCircuits
      alt: altitude
      lat: latitude
      lng: longitude
      url: urlCircuits
  constructors:
    name: "../DATASETS/constructors.csv"
    mergeLogic:
      base: constructorId
      field: constructorId
    rename:
      name: nameConstructors
      nationality: nationalityConstructors
      url: urlConstructors

database:
  sqlScript: "./f1_qualifying.sql"
  user: root
  password: admin
  host: localhost
  port: 3306
  name: f1_qualifying

tables:
  dim_driver:
    driver_nk:
      value: driverId
    driver_ref:
      value: driverRef
      normalize_ref: true
    code:
      value: code
      upper: true
    forename:
      value: forename
      strip: true
      title: true
    surname:
      value: surname
      strip: true
      title: true
    nationality:
      value: nationalityDrivers
      title: true
    number:
      value: number
      int: true
    url:
      value: urlDrivers

  dim_constructor:
    constructor_nk:
      value: constructorId
    constructor_ref:
      value: constructorRef
      normalize_ref: true
    name:
      value: nameConstructors
      strip: true
      title: true
    nationality:
      value: nationalityConstructors
      title: true
    url:
      value: urlConstructors

  dim_circuit:
    circuit_nk:
      value: circuitId
    circuit_ref:
      value: circuitRef
      normalize_ref: true
    name:
      value: nameCircuits
      strip: true
      title: true
    location:
      value: location
      strip: true
      title: true
    country:
      value: countryCircuits
      strip: true
      title: true
    altitude:
      value: altitude
      int: true
    latitude:
      value: latitude
      float: true
      decimals: 6
    longitude:
      value: longitude
      float: true
      decimals: 6
    url:
      value: urlCircuits

  dim_date:
    date:
      value: date
    year: { value: date, date: true }
    month: { value: date, date: true }
    day: { value: date, date: true }

  dim_race:
    race_nk:
      value: raceId
    name:
      value: nameRaces
      strip: true
      title: true
    round:
      value: round
      int: true
    year: { value: date, date: true }
    url:
      value: urlRaces

  fact_qualifying:
    race_id: { fk: dim_race }
    driver_id: { fk: dim_driver }
    constructor_id: { fk: dim_constructor }
    circuit_id: { fk: dim_circuit }
    date_id: { fk: dim_date }

    q1_str:
      value: q1
    q2_str:
      value: q2
    q3_str:
      value: q3

    q1_sec: { value: q1, duration_sec: true }
    q2_sec: { value: q2, duration_sec: true }
    q3_sec: { value: q3, duration_sec: true }

    position:
      value: position

config:
  dim_driver:
    design: dimension
    id: driver_id
    onDuplicate:
      criteria: driver_nk
      method: ignore
    onNull:
      require: [driver_nk, driver_ref, forename, surname]

  dim_constructor:
    design: dimension
    id: constructor_id
    onDuplicate:
      criteria: constructor_nk
      method: ignore
    onNull:
      require: [constructor_nk, constructor_ref, name]

  dim_circuit:
    design: dimension
    id: circuit_id
    onDuplicate:
      criteria: circuit_nk
      method: ignore
    onNull:
      require: [circuit_nk, circuit_ref, name, location, country]

  dim_date:
    design: dimension
    id: date_id
    onDuplicate:
      criteria: [year, month, day]
      method: ignore
    onNull:
      require: [date, year, month, day]

  dim_race:
    design: dimension
    id: race_id
    onDuplicate:
      criteria: race_nk
      method: ignore
    onNull:
      require: [race_nk, name, round, year]

  fact_qualifying:
    design: fact
    id: qualifying_id
    onDuplicate:
      criteria: [race_id, driver_id]
      method: update

    onNull:
      require: [race_id, driver_id, constructor_id, circuit_id, date_id]
